# Generated by Django 5.0.3 on 2024-06-06 19:23

import django.db.models.deletion
import management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=25)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('codigo', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('legenda', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'TipoAvaliacao',
                'verbose_name_plural': 'TipoAvaliacoes',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=23)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('codigo', models.CharField(max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='management.empresa')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='management.filial')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='management.area')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='management.filial')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='management.area')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='management.filial')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='management.ambiente')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='management.area')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='management.filial')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='management.setor')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.AddField(
            model_name='ambiente',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='management.setor'),
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('perguntas', models.ManyToManyField(related_name='formularios', to='management.pergunta')),
                ('tipoavaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TiposAvaliacoes', to='management.tipoavaliacao')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.ambiente')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.filial')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiposcontratos', to='management.setor')),
            ],
            options={
                'verbose_name': 'TipoContrato',
                'verbose_name_plural': 'TiposContratos',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_admissao', models.DateTimeField(blank=True, null=True)),
                ('situacao', models.BooleanField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=15, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateTimeField(blank=True, null=True)),
                ('data_troca_setor', models.DateTimeField(blank=True, null=True)),
                ('data_troca_cargo', models.DateTimeField(blank=True, null=True)),
                ('data_demissao', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=management.models.upload_image_colaborador)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.ambiente')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.area')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.empresa')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.filial')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.setor')),
                ('tipocontrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='management.tipocontrato')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Avaliado',
            fields=[
                ('colaborador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.colaborador')),
                ('formulario', models.ManyToManyField(related_name='avaliados', to='management.formulario')),
            ],
            options={
                'verbose_name': 'Avaliado',
                'verbose_name_plural': 'Avaliados',
            },
            bases=('management.colaborador',),
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('colaborador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.colaborador')),
                ('avaliados', models.ManyToManyField(related_name='avaliadores', to='management.avaliado')),
            ],
            options={
                'verbose_name': 'Avaliador',
                'verbose_name_plural': 'Avaliadores',
            },
            bases=('management.colaborador',),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(blank=True, max_length=60, null=True)),
                ('perguntasRespostas', models.JSONField()),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.BooleanField(blank=True, default=False)),
                ('finished_at', models.DateField(null=True)),
                ('tipoavaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='management.tipoavaliacao')),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_avaliado', to='management.avaliado')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_avaliador', to='management.avaliador')),
            ],
            options={
                'verbose_name': 'Avaliacao',
                'verbose_name_plural': 'Avaliacoes',
            },
        ),
    ]
