# Generated by Django 5.0.3 on 2024-06-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='instrucao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='raca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
