# Generated by Django 5.0.3 on 2024-06-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_colaborador_categoria_colaborador_instrucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='tipocontrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
