# Generated by Django 5.0.3 on 2024-06-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_colaborador_tipocontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='tipoavaliacao',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
