# Generated by Django 5.0.3 on 2024-06-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_avaliacao_tipoavaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='tipoavaliacao',
            new_name='formulario',
        ),
    ]
