# Generated by Django 5.0.3 on 2024-06-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_tipoavaliacao_avaliacao_formulario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='formulario',
            new_name='tipo',
        ),
    ]
