# Generated by Django 5.0.3 on 2024-06-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_formulario_avaliacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='situacao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
